# Generated by Django 4.1.7 on 2023-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_product_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
