# Generated by Django 4.1.7 on 2023-02-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_payment_type',
            field=models.CharField(max_length=10),
        ),
    ]
