# Generated by Django 4.1.7 on 2023-03-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_bill_bill_date_alter_bill_bill_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='category',
            new_name='rep_category',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='rep_date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='price',
            new_name='rep_price',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='product',
            new_name='rep_product',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='quantity',
            new_name='rep_quantity',
        ),
    ]
