# Generated by Django 4.1.7 on 2023-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_rename_category_report_rep_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
